### ISSUE TITLE
F3.2 Implement failure message display all chats

### ISSUE THREAD

**Issue by ZIYANGSONG2003** [ZIYANGSONG2003/AI-Enhanced-WordPress-Development-Toolkit#104]
**Acceptance criteria**

- [ ] Ensure that the error message "Failed to send message. Please try again later" only appears in the specific chat where the message sending failed, not across all chats.
- [ ] Confirm that the message that failed to send is retained in the text field of the specific chat for potential re-sending by the user.

**Comment by 2Jus2** [comment]
LGTM
