### ISSUE TITLE
R1.1 AI plugin selection research

### ISSUE THREAD

**Issue by 2Jus2** [ZIYANGSONG2003/AI-Enhanced-WordPress-Development-Toolkit#14]
Search and find the appropriate AI plugin for this project

**Comment by ZIYANGSONG2003** [comment]
WordPress plug-ins have been captured through the fetch function, and commonly used plug-ins can also be captured, but this function will be used in the AI part later, so it will not be used for the time being.

**Comment by Austin521** [comment]
I think Nicky's idea is correct. We may need to pre-select a few commonly used plugins and then categorize these plugins according to their functions into several major categories. This might help us with our data training.
