### ISSUE TITLE
B1.1Prepare data & use GPT3.5 OR gpt 4.o to train the model

### ISSUE THREAD

**Issue by Guanweiyi1999** [ZIYANGSONG2003/AI-Enhanced-WordPress-Development-Toolkit#144]
- [x] Read the plugin code logic and organize the training data (in a form suitable for GPT3.5)
- [x] After preprocessing the raw data, upload it to OpenAI and initiate a fine-tuning request
- [x]  Continue to monitor the status of the fine-tuning task until the task is completed or failed

**Comment by 2Jus2** [comment]
LGTM

**Comment by BillyHeYifan** [comment]
Organized the training data by thoroughly analyzing the plugin code logic. Extracted relevant information for shortcode generation and structured the dataset in JSONL format. Ensured all data points are validated and consistent, minimizing the risk of formatting errors during the fine-tuning process.
