### ISSUE TITLE
B1.8 Uploaded a script to check if the file to be pushed to git is too large and all the scp upload command codes

### ISSUE THREAD

**Issue by ZIYANGSONG2003** [ZIYANGSONG2003/AI-Enhanced-WordPress-Development-Toolkit#156]

**Comment by ZIYANGSONG2003** [comment]
- [x] Successfully ran the plugin in vscode
- [x] The initial code and dataset have been uploaded to GitHub.
- [x] Can check if the file to be pushed to git is too large and all the scp upload command codes
- [x] No problem after testing

**Comment by 2Jus2** [comment]
LGTM
