### ISSUE TITLE
G1.1 Initiate the Project Repo/Onboarding - 24s1

### ISSUE THREAD

**Issue by 2Jus2** [ZIYANGSONG2003/AI-Enhanced-WordPress-Development-Toolkit#3]
### Complete Initial Project Documentation 

- [x] Statement of Work
- [x] Team Charter
- [x] Landing Page
- [x] Roadmap
- [x] Other relevant documentations

### Team Organisation
- [x] Assign each team member to specific roles and tasks.
- [x] Ensure clarity of responsibilities among team members.
- [x] Assign each team member with peer-review member.

Key Performance Indicator (KPI)
- [x] Achieve 100% completion of the initial preparation tasks.

## Onboarding and Repository Setup Milestone (24s1)
- [x] All documentations are completed (Statement of Work, Team Charter, Landing Page, Roadmap, and etc).
- [x] All team members are assigned and understand their specific roles and tasks.
- [x] All new members have joined the GitHub organisation and set up their development environments locally.
- [x] Invite stakeholders(shadow team, tutor, examiner) to have the access to both Github repo and Confluence.

**Comment by 2Jus2** [comment]
Complete all the require documentation

**Comment by Austin521** [comment]
> Complete all the require documentation

Yes, I also think that our group has already completed 90% of our task. We still need to check some documents more carefully and make some supplements.

**Comment by casey123321** [comment]
In response to the last audit, I'd like to be able to rewind all the files to make it more complete
