### ISSUE TITLE
F2.2 Bug Fixing: User icon's placement

### ISSUE THREAD

**Issue by 2Jus2** [ZIYANGSONG2003/AI-Enhanced-WordPress-Development-Toolkit#39]
**Description**
The position of the user icon would change with the length of the input text. Set a message function, and within this function, by reasonably dividing intervals and adding UserMessageWrapper and message content CSS classes

**Acceptance criteria**

- [x] Ensure the position of the user icon is always a fixed distance from the left side of the main content
- [ ] Ensure the user's input content always follows directly after the user icon.

**Comment by ZIYANGSONG2003** [comment]
Although there are a few minor flaws, it is usable and can be changed later, but for now there are no problems and it is enough.
