### ISSUE TITLE
F2.5 Bug Fixing: Plugin list from a previous session still displays after starting a new chat

### ISSUE THREAD

**Issue by 2Jus2** [ZIYANGSONG2003/AI-Enhanced-WordPress-Development-Toolkit#42]
Acceptance criteria 

- [x] Modify fetchPlugins to clear everything from the previous page when opening a new page (clicking new chat)

**Comment by ZIYANGSONG2003** [comment]
Generally speaking, there are no problems. If there are any problems later, I will open a new issue, so for now.
