### ISSUE TITLE
B2.1 AWS Lambda function implementing the GPT model API

### ISSUE THREAD

**Issue by 2Jus2** [ZIYANGSONG2003/AI-Enhanced-WordPress-Development-Toolkit#45]
**Description**
Develop an AWS Lambda function to call the GPT model API

**Acceptance criteria**

- [x] Ensure handle the request from the Flask app and forward it to the GPT model API, then return the GPT model's response.

**Comment by casey123321** [comment]
Evaluate the technical feasibility of using AWS Lambda functions to call GPT model APIs, including the stability of the APIs, the performance limitations of the Lambda functions, and the challenges that may be encountered in actual deployments.

Considering that invoking the GPT model may involve sensitive data, shadow team may perform an in-depth analysis of the security of the data transfer and the compliance of the data processing and storage.
