### ISSUE TITLE
G1.4 Documentation of ticketing system issue category

### ISSUE THREAD

**Issue by 2Jus2** [ZIYANGSONG2003/AI-Enhanced-WordPress-Development-Toolkit#90]
**Acceptance criteria**

- [ ] As a team member, I want to have a documentation that outline the ticketing system's each category and what it represents, so that I can easily record the issue in specific category.

**Comment by Austin521** [comment]
I think this idea is quite good, Stephanie, what is your plan?

**Comment by 2Jus2** [comment]
I've upload the documentation for this , plz have a look on the project manager folder :)

**Comment by Austin521** [comment]
> I've upload the documentation for this , plz have a look on the project manager folder :)

LGTM
