### ISSUE TITLE
R2.6 Research on Devin

### ISSUE THREAD

**Issue by 2Jus2** [ZIYANGSONG2003/AI-Enhanced-WordPress-Development-Toolkit#92]
**Description**

The examiner (Liang) mentioned that there exists an AI software engineer named Devin and is relevant to what we are currently doing, thus, it is required to conduct a research on Devin 

- Investigate any common between Devin and AI-Enhanced 
- Investigate the models that Devin use 
- Pros on use Devin 
- Ethical considerations on Devin

**Comment by Austin521** [comment]
Regarding the first point, I believe Devin is the forefront of our project. We may need a simple intelligence to help us process received natural language. On this point, I think this simple intelligence should have inductive ability. For example, the natural language might be "I want a button that's pitch black but interspersed with maple-like red", then after being processed by the simple intelligence, the sentence should be "I want a button where 3/4 of its large circular area is gray-black and 1/4 of its central circular area is maple leaf red". Such preprocessing can reduce AI workload for backend when searching for similar templates.

**Comment by 2Jus2** [comment]
Upload the documentation for Devin on Project Manager folder
